### ISSUE TITLE
Can't receive either lama_get_test_data or lama_get_tutorial_data

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#1]
Hi everyone,

I've just recently installed LAMA-0.9.2 on a Windows 10 desktop via the Ubuntu app: 

>pip3 install lama_phenotype_detection
Collecting lama_phenotype_detection
  Using cached https://files.pythonhosted.org/packages/c1/6b/8e5e324e7015ff2b1b3e034bb4061f75200753dc6f7a4fbc5728978fb28b/lama_phenotype_detection-0.9.2-py3-none-any.whl
Collecting pandas>=0.23.4 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/52/3f/f6a428599e0d4497e1595030965b5ba455fd8ade6e977e3c819973c4b41d/pandas-0.25.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting statsmodels>=0.9.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/48/f9/9f5c93b0159d89dd527ed271ca2ad71af629422d89530218c5e929c5f800/statsmodels-0.10.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting filelock (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting psutil (from lama_phenotype_detection)
Collecting numpy>=1.15.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.1.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/54/18/d7c101d5e93b6c78dc206fcdf7bd04c1f8138a7b1a93578158fa3b132b08/scipy-1.3.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pynrrd (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/6d/3b/9935799ebe6c9e3b4f2b7709491a7831d558a6f9579f5211a7ce6bab2bc0/pynrrd-0.4.1-py2.py3-none-any.whl
Collecting scikit-learn>=0.19.2 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/2e/d0/860c4f6a7027e00acff373d9f5327f4ae3ed5872234b3cbdd7bcb52e5eff/scikit_learn-0.22-cp36-cp36m-manylinux1_x86_64.whl
Collecting pytest (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/da/ed/d22d7f06eb1107271694ed2171b9d52e8eea38d9757124e75ba13324ac77/pytest-5.3.1-py3-none-any.whl
Collecting scikit-image>=0.15.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/c8/bb/771800366f41d66eef51e4b80515f8ef7edab234a3f244fdce3bafe89b39/scikit_image-0.16.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting PyYAML>=3.13 (from lama_phenotype_detection)
Collecting toml (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting SimpleITK>=1.1.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f8/d8/53338c34f71020725ffb3557846c80af96c29c03bc883551a2565aa68a7c/SimpleITK-1.2.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting appdirs (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting matplotlib>=2.2.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/4e/11/06958a2b895a3853206dea1fb2a5b11bf044f626f90745987612af9c8f2c/matplotlib-3.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting logzero (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/97/24/27295d318ea8976b12cf9cc51d82e7c7129220f6a3cc9e3443df3be8afdb/logzero-1.5.0-py2.py3-none-any.whl
Collecting seaborn>=0.9.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a8/76/220ba4420459d9c4c9c9587c6ce607bf56c25b3d3d2de62056efe482dadc/seaborn-0.9.0-py3-none-any.whl
Collecting addict (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/14/6f/beb258220417c1a0fe11e842f2e012a1be7eeeaa72a1d10ba17a804da367/addict-2.2.1-py3-none-any.whl
Collecting pytz>=2017.2 (from pandas>=0.23.4->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.6.1 (from pandas>=0.23.4->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting patsy>=0.4.0 (from statsmodels>=0.9.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ea/0c/5f61f1a3d4385d6bf83b83ea495068857ff8dfb89e74824c6e9eb63286d8/patsy-0.5.1-py2.py3-none-any.whl
Collecting joblib>=0.11 (from scikit-learn>=0.19.2->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/8f/42/155696f85f344c066e17af287359c9786b436b1bf86029bb3411283274f3/joblib-0.14.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f1/21/2acdb795468a74fdbf9abbe2fc8448127347e13a3aff3caf860c1e798823/importlib_metadata-1.1.2-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting packaging (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/5c/1d/3df99de956abb96305956e09e6a1fa955883295e1f28808f9c97b3d5364d/more_itertools-8.0.0-py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting wcwidth (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting networkx>=2.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl
Collecting PyWavelets>=0.4.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/59/bb/d2b85265ec9fa3c1922210c9393d4cdf7075cc87cce6fe671d7455f80fbc/PyWavelets-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting imageio>=2.3.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/1a/de/f7f985018f462ceeffada7f6e609919fbcc934acd9301929cba14bc2c24a/imageio-2.6.1-py3-none-any.whl
Collecting pillow>=4.3.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas>=0.23.4->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl
Installing collected packages: numpy, pytz, six, python-dateutil, pandas, patsy, scipy, statsmodels, filelock, psutil, pynrrd, joblib, scikit-learn, py, more-itertools, zipp, importlib-metadata, pluggy, pyparsing, packaging, attrs, wcwidth, pytest, decorator, networkx, PyWavelets, pillow, imageio, cycler, setuptools, kiwisolver, matplotlib, scikit-image, PyYAML, toml, SimpleITK, appdirs, logzero, seaborn, addict, lama-phenotype-detection
Successfully installed PyWavelets-1.1.1 PyYAML-5.2 SimpleITK-1.2.4 addict-2.2.1 appdirs-1.4.3 attrs-19.3.0 cycler-0.10.0 decorator-4.4.1 filelock-3.0.12 imageio-2.6.1 importlib-metadata-1.1.2 joblib-0.14.0 kiwisolver-1.1.0 lama-phenotype-detection-0.9.2 logzero-1.5.0 matplotlib-3.1.2 more-itertools-8.0.0 networkx-2.4 numpy-1.17.4 packaging-19.2 pandas-0.25.3 patsy-0.5.1 pillow-6.2.1 pluggy-0.13.1 psutil-5.6.7 py-1.8.0 pynrrd-0.4.1 pyparsing-2.4.5 pytest-5.3.1 python-dateutil-2.8.1 pytz-2019.3 scikit-image-0.16.2 scikit-learn-0.22 scipy-1.3.3 seaborn-0.9.0 setuptools-42.0.2 six-1.13.0 statsmodels-0.10.2 toml-0.10.0 wcwidth-0.1.7 zipp-0.6.0

I can't run the tutorial, however, as these files weren't downloaded on install and lama_get_test_data runs into a HTTPS 404 error: 

> lama_reg -c tests/test_data/population_average_data/registration_config_population_average.yaml
[W 191205 12:48:14 glcm3d:14] pyradiomics not installed. No glcms will be made
[E 191205 12:48:14 run_lama:159] Cannot open LAMA config file: tests/test_data/population_average_data/registration_config_population_average.yaml
    [Errno 2] No such file or directory: 'tests/test_data/population_average_data/registration_config_population_average.yaml'
[E 191205 12:48:14 common:130] Traceback (most recent call last):
      File "/home/kyle_arkell/.local/bin/lama_reg", line 11, in <module>
        sys.exit(main())
      File "/home/kyle_arkell/.local/lib/python3.6/site-packages/scripts/lama_reg.py", line 19, in main
        run_lama.run(Path(args.config))
      File "/home/kyle_arkell/.local/lib/python3.6/site-packages/lama/registration_pipeline/run_lama.py", line 157, in run
        config = LamaConfig(configfile)
      File "/home/kyle_arkell/.local/lib/python3.6/site-packages/lama/registration_pipeline/validate_config.py", line 45, in __init__
        with open(config_path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_data/population_average_data/registration_config_population_average.yaml'
    NoneType: None
[W 191205 12:48:14 common:131] ##############################
[W 191205 12:48:14 common:132]

[W 191205 12:48:14 common:134] Lama encountered a problem with reading or interpreting some data. Please check the log files

> lama_get_test_data
Downloading data
Traceback (most recent call last):
  File "/home/kyle_arkell/.local/bin/lama_get_test_data", line 11, in <module>
    sys.exit(main())
  File "/home/kyle_arkell/.local/lib/python3.6/site-packages/scripts/lama_get_test_data.py", line 9, in main
    download_and_extract_zip(url, test_dir)
  File "/home/kyle_arkell/.local/lib/python3.6/site-packages/lama/common.py", line 880, in download_and_extract_zip
    remotezip = urllib.request.urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

I'm concerned that LAMA didn't install properly, especially when looking at the verbose output from pip: 
>pip3 -v install lama_phenotype_detection | tee 2&>1 lama_install.log
[lama_install.log.txt](https://github.com/mpi2/LAMA/files/3924762/lama_install.log.txt)

which indicates that automated_annotation.py and test_normalisation.py didn't compile - is this normal?: 
  *** Error compiling '/tmp/pip-build-vcjxd5re/lama-phenotype-detection/lama/stats/automated_annotation.py'...
    File "/tmp/pip-build-vcjxd5re/lama-phenotype-detection/lama/stats/automated_annotation.py", line 27
      def __init__(self, label_map: , label_info, stats, outpath, type='jacobians'):
                                    ^
  SyntaxError: invalid syntax

  *** Error compiling '/tmp/pip-build-vcjxd5re/lama-phenotype-detection/tests/test_normalisation.py'...
  Sorry: IndentationError: expected an indented block (test_normalisation.py, line 7)

I've tried installing via the git but I can't find Pipfile, scripts/ or utilities/ from the latest git

Kind Regards,
Kyle Drover

**Comment by nrhorner** [comment]
Hi Kyle,

I've not looked at the tutorial data fro a bit. Let me fix that and I'll get back to you.

**Comment by nrhorner** [comment]
Hi Kyle,

If you're still interested, I fixed the tutorials/wlakthroughs.

**Comment by Dorky-Lever** [comment]
Hi Neil, 

I installed lama on a separate machine via the Windows Ubuntu app. 

I followed the steps in the getting stated wiki but had to manually pip install pyradiomics.

I've installed all of the dependencies and they give the correct output and the $PATH and $LD_LIBRARY PATHS have been added. 

However, when I try to download the walkthrough data, I get the following error: 
>lama_get_walkthrough_data
Downloading data
Traceback (most recent call last):
  File "/home/kyle/.local/bin/lama_get_walkthrough_data", line 11, in <module>
    sys.exit(main())
  File "/home/kyle/.local/lib/python3.6/site-packages/lama/scripts/lama_get_walkthrough_data.py", line 18, in main
    download_and_extract_zip(url, unzip_dir)
  File "/home/kyle/.local/lib/python3.6/site-packages/lama/common.py", line 882, in download_and_extract_zip
    zipinmemory = io.BytesIO(remotezip.read())
  File "/usr/lib/python3.6/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 624, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(27725072 bytes read, 1759259526 more expected)


Is there any test-data for LAMA that will work for Windows?  I currently don't have access to a Linux machine and I can't update Python and R on my computing cluster without having to play around with a virtual environment. 

Kind Regards, 
Kyle Drover

This is the run of my install: 


>pip3 install lama_phenotype_detection --user
Collecting lama_phenotype_detection
  Using cached https://files.pythonhosted.org/packages/8d/38/59ff3b6b9d4e62d981e3854be9b1f731171265fe39383de28ee6046758b5/lama_phenotype_detection-0.9.42-py3-none-any.whl
Collecting matplotlib>=2.2.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/93/4b/52da6b1523d5139d04e02d9e26ceda6146b48f2a4e5d2abfdf1c7bac8c40/matplotlib-3.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting addict (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/14/6f/beb258220417c1a0fe11e842f2e012a1be7eeeaa72a1d10ba17a804da367/addict-2.2.1-py3-none-any.whl
Collecting pytest (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/6c/f9/9f2b6c672c8f8bb87a4c1bd52c1b57213627b035305aad745d015b2a62ae/pytest-5.4.2-py3-none-any.whl
Collecting logzero (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/97/24/27295d318ea8976b12cf9cc51d82e7c7129220f6a3cc9e3443df3be8afdb/logzero-1.5.0-py2.py3-none-any.whl
Collecting seaborn>=0.9.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/c7/e6/54aaaafd0b87f51dfba92ba73da94151aa3bc179e5fe88fc5dfb3038e860/seaborn-0.10.1-py3-none-any.whl
Collecting PyYAML>=3.13 (from lama_phenotype_detection)
Collecting scipy>=1.1.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting scikit-image>=0.15.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/0e/ba/53e1bfbdfd0f94514d71502e3acea494a8b4b57c457adbc333ef386485da/scikit_image-0.17.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting scikit-learn>=0.19.2 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/d9/3a/eb8d7bbe28f4787d140bb9df685b7d5bf6115c0e2a969def4027144e98b6/scikit_learn-0.23.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting psutil (from lama_phenotype_detection)
Collecting filelock (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting appdirs (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting SimpleITK>=1.1.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f8/d8/53338c34f71020725ffb3557846c80af96c29c03bc883551a2565aa68a7c/SimpleITK-1.2.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting toml (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
Collecting numpy>=1.15.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/03/27/e35e7c6e6a52fab9fcc64fc2b20c6b516eba930bb02b10ace3b38200d3ab/numpy-1.18.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting pandas>=0.23.4 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/bb/71/8f53bdbcbc67c912b888b40def255767e475402e9df64050019149b1a943/pandas-1.0.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pynrrd (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/92/00/ef17d52fd125f357d7ead95e823091b2344194d34ce94e2fe839184f48e7/pynrrd-0.4.2-py2.py3-none-any.whl
Collecting statsmodels>=0.9.0 (from lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/cb/83/540fd83238a18abe6c2d280fa8e489ac5fcefa1f370f0ca1acd16ae1b860/statsmodels-0.11.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ae/23/147de658aabbf968324551ea22c0c13a00284c4ef49a77002e91f79657b7/kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
Collecting packaging (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/06/b1/2dcadc4861c505a807d5c6d88928450fe5afcf352f205432572a10d74657/more_itertools-8.3.0-py3-none-any.whl
Collecting wcwidth (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl
Collecting imageio>=2.3.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/4c/2b/9dd19644f871b10f7e32eb2dbd6b45149c350b4d5f2893e091b882e03ab7/imageio-2.8.0-py3-none-any.whl
Collecting PyWavelets>=1.1.1 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/59/bb/d2b85265ec9fa3c1922210c9393d4cdf7075cc87cce6fe671d7455f80fbc/PyWavelets-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting networkx>=2.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/e0/50/8e78e6f62ffa50d6ca95c281d5a2819bef66d023ac1b723e253de5bda9c5/Pillow-7.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting tifffile>=2019.7.26 (from scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/96/2f/d2634e5823deb11dfb072017dfca7d6040d55de1d6b9f0b266b653da6da9/tifffile-2020.5.25-py3-none-any.whl
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.19.2->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/db/09/cab2f398e28e9f183714afde872b2ce23629f5833e467b151f18e1e08908/threadpoolctl-2.0.0-py3-none-any.whl
Collecting joblib>=0.11 (from scikit-learn>=0.19.2->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/b8/a6/d1a816b89aa1e9e96bcb298eb1ee1854f21662ebc6d55ffa3d7b3b50122b/joblib-0.15.1-py3-none-any.whl
Collecting pytz>=2017.2 (from pandas>=0.23.4->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting patsy>=0.5 (from statsmodels>=0.9.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ea/0c/5f61f1a3d4385d6bf83b83ea495068857ff8dfb89e74824c6e9eb63286d8/patsy-0.5.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib>=2.2.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image>=0.15.0->lama_phenotype_detection)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, numpy, kiwisolver, cycler, pyparsing, matplotlib, addict, zipp, importlib-metadata, packaging, more-itertools, wcwidth, pluggy, attrs, py, pytest, logzero, pytz, pandas, scipy, seaborn, PyYAML, pillow, imageio, PyWavelets, decorator, networkx, tifffile, scikit-image, threadpoolctl, joblib, scikit-learn, psutil, filelock, appdirs, SimpleITK, toml, pynrrd, patsy, statsmodels, lama-phenotype-detection
Successfully installed PyWavelets-1.1.1 PyYAML-5.3.1 SimpleITK-1.2.4 addict-2.2.1 appdirs-1.4.4 attrs-19.3.0 cycler-0.10.0 decorator-4.4.2 filelock-3.0.12 imageio-2.8.0 importlib-metadata-1.6.0 joblib-0.15.1 kiwisolver-1.2.0 lama-phenotype-detection-0.9.42 logzero-1.5.0 matplotlib-3.2.1 more-itertools-8.3.0 networkx-2.4 numpy-1.18.4 packaging-20.4 pandas-1.0.3 patsy-0.5.1 pillow-7.1.2 pluggy-0.13.1 psutil-5.7.0 py-1.8.1 pynrrd-0.4.2 pyparsing-2.4.7 pytest-5.4.2 python-dateutil-2.8.1 pytz-2020.1 scikit-image-0.17.2 scikit-learn-0.23.1 scipy-1.4.1 seaborn-0.10.1 six-1.15.0 statsmodels-0.11.1 threadpoolctl-2.0.0 tifffile-2020.5.25 toml-0.10.1 wcwidth-0.1.9 zipp-3.1.0

**Comment by Dorky-Lever** [comment]
Hi Neil,

I fixed the issue by temporarily changing the HTTP version in download_and_extract_zip (see pull request). 

Kind Regards, 
Kyle Drover
