### ISSUE TITLE
Windows Anaconda: pip install lama_phenotype_detection fails to install pyradiomics

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#13]
Hi guys, 

I followed the steps outlined in the wiki for installing LAMA within windows. Anaconda = Python 3.6, R = version 4.0.0 and elastix was successfully installed (shown below) 

(C:\Users\Kyle\Anaconda3) C:\Users\Kyle>elastix
Use "elastix --help" for information about elastix-usage.

Running pip install lama_phenotype_detections fails to install pyradiomics due to a version conflict between scikit and Pywavelets 1.0.0.  This can be fixed by manually installing pyradiomics (I wasn't able to edit the wiki to make this change). 

**Install before manually installing pyradiomics**

(C:\Users\Kyle\Anaconda3) C:\Users\Kyle>pip install lama_phenotype_detection
Collecting lama_phenotype_detection
  Downloading lama_phenotype_detection-0.9.51-py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 2.2 MB/s
Requirement already satisfied: pandas>=0.23.4 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.0.3)
Requirement already satisfied: logzero in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.5.0)
Requirement already satisfied: pytest in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (3.0.7)
Requirement already satisfied: scikit-learn>=0.19.2 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.23.1)
Requirement already satisfied: numpy>=1.15.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.18.4)
Requirement already satisfied: PyYAML>=3.13 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (5.3.1)
Requirement already satisfied: toml in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.10.1)
Requirement already satisfied: addict in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (2.2.1)
Requirement already satisfied: seaborn>=0.9.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.10.1)
Requirement already satisfied: psutil in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (5.2.2)
Requirement already satisfied: scipy>=1.1.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.4.1)
Requirement already satisfied: filelock in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (3.0.12)
Requirement already satisfied: scikit-image>=0.15.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.17.2)
Requirement already satisfied: appdirs in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.4.4)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.11.1)
Requirement already satisfied: SimpleITK>=1.1.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (1.2.4)
Requirement already satisfied: pynrrd in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (0.4.2)
Requirement already satisfied: matplotlib>=2.2.0 in c:\users\kyle\anaconda3\lib\site-packages (from lama_phenotype_detection) (3.2.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\kyle\anaconda3\lib\site-packages (from pandas>=0.23.4->lama_phenotype_detection) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\kyle\anaconda3\lib\site-packages (from pandas>=0.23.4->lama_phenotype_detection) (2017.2)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\kyle\anaconda3\lib\site-packages (from logzero->lama_phenotype_detection) (0.3.9)
Requirement already satisfied: py>=1.4.29 in c:\users\kyle\anaconda3\lib\site-packages (from pytest->lama_phenotype_detection) (1.4.33)
Requirement already satisfied: setuptools in c:\users\kyle\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg (from pytest->lama_phenotype_detection) (27.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-learn>=0.19.2->lama_phenotype_detection) (0.15.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-learn>=0.19.2->lama_phenotype_detection) (2.0.0)
Requirement already satisfied: imageio>=2.3.0 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-image>=0.15.0->lama_phenotype_detection) (2.8.0)
Requirement already satisfied: networkx>=2.0 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-image>=0.15.0->lama_phenotype_detection) (2.4)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-image>=0.15.0->lama_phenotype_detection) (7.1.2)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-image>=0.15.0->lama_phenotype_detection) (2020.5.25)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\kyle\anaconda3\lib\site-packages (from scikit-image>=0.15.0->lama_phenotype_detection) (1.1.1)
Requirement already satisfied: patsy>=0.5 in c:\users\kyle\anaconda3\lib\site-packages (from statsmodels>=0.9.0->lama_phenotype_detection) (0.5.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kyle\anaconda3\lib\site-packages (from matplotlib>=2.2.0->lama_phenotype_detection) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\kyle\anaconda3\lib\site-packages (from matplotlib>=2.2.0->lama_phenotype_detection) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\kyle\anaconda3\lib\site-packages (from matplotlib>=2.2.0->lama_phenotype_detection) (2.1.4)
Requirement already satisfied: six>=1.5 in c:\users\kyle\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.23.4->lama_phenotype_detection) (1.10.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\kyle\anaconda3\lib\site-packages (from networkx>=2.0->scikit-image>=0.15.0->lama_phenotype_detection) (4.4.2)
Installing collected packages: lama-phenotype-detection
Successfully installed lama-phenotype-detection-0.9.51

(C:\Users\Kyle\Anaconda3) C:\Users\Kyle>lama_reg
[W 200624 16:58:28 glcm3d:14] pyradiomics not installed. No glcms will be made
usage: The LAMA registration pipeline [-h] -c CONFIG
The LAMA registration pipeline: error: the following arguments are required: -c

**Install after manually installing pyradiomics**

(C:\Users\Kyle\Anaconda3) C:\Users\Kyle>pip install pyradiomics
Collecting pyradiomics
  Using cached pyradiomics-3.0-cp36-cp36m-win_amd64.whl (121 kB)
Requirement already satisfied: numpy>=1.9.2 in c:\users\kyle\anaconda3\lib\site-packages (from pyradiomics) (1.18.4)
Requirement already satisfied: pykwalify>=1.6.0 in c:\users\kyle\anaconda3\lib\site-packages (from pyradiomics) (1.7.0)
Requirement already satisfied: six>=1.10.0 in c:\users\kyle\anaconda3\lib\site-packages (from pyradiomics) (1.10.0)
Requirement already satisfied: SimpleITK>=0.9.1 in c:\users\kyle\anaconda3\lib\site-packages (from pyradiomics) (1.2.4)
Collecting PyWavelets<=1.0.0,>=0.4.0
  Using cached PyWavelets-1.0.0-cp36-none-win_amd64.whl (4.2 MB)
Requirement already satisfied: PyYAML>=3.11 in c:\users\kyle\anaconda3\lib\site-packages (from pykwalify>=1.6.0->pyradiomics) (5.3.1)
Requirement already satisfied: python-dateutil>=2.4.2 in c:\users\kyle\anaconda3\lib\site-packages (from pykwalify>=1.6.0->pyradiomics) (2.8.1)
Requirement already satisfied: docopt>=0.6.2 in c:\users\kyle\anaconda3\lib\site-packages (from pykwalify>=1.6.0->pyradiomics) (0.6.2)
ERROR: scikit-image 0.17.2 has requirement PyWavelets>=1.1.1, but you'll have pywavelets 1.0.0 which is incompatible.
Installing collected packages: PyWavelets, pyradiomics
  Attempting uninstall: PyWavelets
    Found existing installation: PyWavelets 1.1.1
    Uninstalling PyWavelets-1.1.1:
      Successfully uninstalled PyWavelets-1.1.1
Successfully installed PyWavelets-1.0.0 pyradiomics-3.0

(C:\Users\Kyle\Anaconda3) C:\Users\Kyle>lama_reg
usage: The LAMA registration pipeline [-h] -c CONFIG
The LAMA registration pipeline: error: the following arguments are required: -c

**Comment by nrhorner** [comment]
Pyradiomics is not needed at the moment. I am hoping to add texture-based analysis in the near future.

**Comment by nrhorner** [comment]
I'll remove it from the dependencies

**Comment by nrhorner** [comment]
I've updated the wiki with your suggestion https://github.com/mpi2/LAMA/wiki/getting-started. Thansk
