### ISSUE TITLE
Windows Anaconda: lama_reg -c causes lama.registration_pipeline.validate_config.LamaConfigError

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#14]
Hi guys, 

After performing the following on a fresh install within Anaconda 
 

1. Running pip install lama_phenotype_detection and pip install pyradiomics

2. Editing LAMA/common.py to fix an incomplete read error during downloading the walk-through data (as outlined in https://github.com/mpi2/LAMA/pull/12)  and then downloading the walk-through data
 
3.  cd'ing to lama_walkthroughs\data\population_average\ 

I ran each of the commands specified within the population_average.sh walkthrough i.e. 

    $lama_img_info -i inputs

    $lama_pad_volumes -i inputs  

    $lama_img_info -i inputs
                                                              

    name       size    z    y    x  min  max    mean          spacing           origin  dtype
    0   20131025_CBX2_E14.5_12.1g_WT_XY_rec_scaled_6.8627_pixel_13.nrrd  215804600  932  550  421    0  206  13.281  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
    1   20131028_CBX2_E14.5_12.1f_WT_XY_rec_scaled_7.1066_pixel_14.nrrd  215804600  932  550  421    0  196  11.028  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
    2  20131206_MLLT3_E14.5_15.3d_WT_XY_rec_scaled_5.1471_pixel_14.nrrd  215804600  932  550  421    0  216  13.321  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
    3  20140107_MLLT3_E14.5_16.3e_wt_XY_rec_scaled_5.1471_pixel_14.nrrd  215804600  932  550  421    0  185  11.702  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
    4   20140121_RIC8B_E14.5_15.4b_wt_xy_rec_scaled_3.125_pixel_14.nrrd  215804600  932  550  421    0  230  11.693  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
     5   20140121_RIC8B_E14.5_15.5h_wt_XX_rec_scaled_3.125_pixel_14.nrrd  215804600  932  550  421    0  237  10.195  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
     6   20140221_FGF10_E14.5_14.2d_WT_XY_rec_scaled_3.125_pixel_14.nrrd  215804600  932  550  421    0  254  15.238  (1.0, 1.0, 
    1.0)  (0.0, 0.0, 0.0)  uint8
     7                 20140409_ATG3_E14.5_18.2h_WT_XY_REC_scaled_2.nrrd  215804600  932  550  421    0  255  14.416  (1.0, 1.0, 1.0)  
    (0.0, 0.0, 0.0)  uint8

    max dimensions (z: 932, y: 550, x: 421)

**but lama_reg -c could not read the pop_avg.toml file (file can be read within nano / notepad so it doesn't seem corrupted)** 

(base) C:\Users\u5823099\lama_walkthroughs\data\population_average>lama_reg -c pop_avg.toml
[E 200624 17:25:13 common:107] Traceback (most recent call last):
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\common.py", line 943, in cfg_load
        return toml.load(cfg)
      File "c:\users\u5823099\anaconda3\lib\site-packages\toml\decoder.py", line 134, in load
        return loads(ffile.read(), _dict, decoder)
      File "c:\users\u5823099\anaconda3\lib\site-packages\toml\decoder.py", line 214, in loads
        " Reached end of line.", original, i)
    toml.decoder.TomlDecodeError: Key name found without value. Reached end of line. (line 10 column 2 char 293)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\registration_pipeline\run_lama.py", line 154, in run
        config = LamaConfig(configfile)
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\registration_pipeline\validate_config.py", line 44, in __init__
        self.config = common.cfg_load(config_path)
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\common.py", line 945, in cfg_load
        raise ValueError("can't read the config file - {}".format(e))
    ValueError: can't read the config file - Key name found without value. Reached end of line. (line 10 column 2 char 293)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\u5823099\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\users\u5823099\anaconda3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\u5823099\Anaconda3\Scripts\lama_reg.exe\__main__.py", line 7, in <module>
        sys.exit(main())
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\scripts\lama_reg.py", line 19, in main
        run_lama.run(Path(args.config))
      File "c:\users\u5823099\anaconda3\lib\site-packages\lama\registration_pipeline\run_lama.py", line 159, in run
        raise(LamaConfigError(e))
    lama.registration_pipeline.validate_config.LamaConfigError: can't read the config file - Key name found without value. Reached end of line. (line 10 column 2 char 293)
    NoneType: None
[W 200624 17:25:13 common:108] ##############################
[W 200624 17:25:13 common:111] Lama encountered a problem with reading or interpreting some data. Please check the log files

(base) C:\Users\u5823099\lama_walkthroughs\data\population_average>

**Comment by Dorky-Lever** [comment]
So I think I found the problem. my pop_avg.toml file that I downloaded contained a random "2" that wasn't assigned to any variable. Deleting the 2 seems to start the rigid registration step.

**Comment by nrhorner** [comment]
There was indeed a stray "2" in there. It's removed
