### ISSUE TITLE
Could you add this to the getting started wiki please?

### ISSUE THREAD

**Issue by Dorky-Lever** [mpi2/LAMA#17]
Hi Everyone,

Some members of the National Computing Infrastructure (NCI) and I may have fixed the issue with running LAMA on NCI clusters (my qsub population_average.sh with no read -p has been running for an  3 hours). 

Could this be added to wiki please - I think this should work?

#If you're trying to install LAMA on a National Computing Infrastructure (NCI) computing cluster, ~/.profile does not exist. 
instead, run the following code: 

export PATH=$HOME/.local/bin:$PATH

Also people qsubbing the walk-through files will need different bash files that require no input and have a slightly different parent_path (example attached below). 

[population_average.sh.txt](https://github.com/mpi2/LAMA/files/5072385/population_average.sh.txt)

**Comment by nrhorner** [comment]
I've added both these issues to to the [getting_started](/getting_started) page.
